name: dog_training_app
description: A dog separation anxiety training app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  fl_chart: ^0.64.0

flutter:
  uses-material-design: true
